### ISSUE TITLE
Does sleep work correctly?

### ISSUE THREAD

**Issue by RitaLee79** [Toooorch/X99-Deluxe-II#2]
Hi, I´m trying to configure sleep in my hackintosh but usb are ejected unsafely after sleeping.
I'd like to ask if in your configuration it's working correctly.

Thanks

**Comment by Toooorch** [comment]
Hey, I don’t use sleep at all but without PMDrvr.kext (which can also cause issues like this) it would work. Sleep can be really tricky...
