### ISSUE TITLE
Have you tried to install 10.14.x/10.15.x?

### ISSUE THREAD

**Issue by banguit** [Toooorch/X99-Deluxe-II#4]
Hi Michal!

Have you tried to install 10.14.x/10.15.x on these hardware? If yes, could you please share your EFI folder?

Best regards,
Dima

**Comment by Toooorch** [comment]
Hey Dima,

unfortunately, no - I no longer use macOS and If you have Nvidia graphic card don't even try 10.14.x/10.15.x.

**Comment by banguit** [comment]
Thanks for the answer Michael!
